title: Analysis of the Starwars Universe
description: Using Wookieepedia and movie transcripts
remote_theme: jeromelachaud/grayscale-theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-remote-theme
