title: Analysis of the Starwars Universe
description: Using Wookieepedia and movie transcripts
remote_theme: broccolini/swiss
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-remote-theme
